### PR TITLE
Fix issue #39

### PR DESCRIPTION
**Pull request by dmitriim**

### CODE REVIEW

**Comment by brendanheywood** [comment]
This all looks good, the only question is wether this should land in master or we move this plugin to the new stable branch names

**Comment by dmitriim** [comment]
Do you see anything that could be broken? It's mostly refactoring for the code. There should be any breaking changes.
I have CI for 3.5, 3.9, 3.10 and 3.11. Unfortunately it doesn't check a lot. At least the plugin can be installed. :)  I can add more tests to make sure it's not broken for 3.5

**Comment by brendanheywood** [comment]
My main concern would be totara 11

**Comment by dmitriim** [comment]
ah! very good point. Will create a branch for totara.

**Comment by dmitriim** [comment]
Actually I have checked and this plugin requires Moodle 3.3+. Means we don't run it in totara 11. It should work k for totara 12 though.

**Comment by dmitriim** [comment]
I have created https://github.com/catalyst/moodle-tool_webanalytics/issues/42

**Pull request merged**
